-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  Migration 002: Seed cost_codes from the BuilderTrend export           ║
-- ║                                                                        ║
-- ║  GENERATED FILE — do not hand-edit.                                    ║
-- ║  Source:    BTCostCodes_20260929.xlsx                                  ║
-- ║  Generator: scripts/gen_cost_code_seed.py                              ║
-- ║  Rows:      236                                                        ║
-- ║                                                                        ║
-- ║  Idempotent: ON CONFLICT (code) DO UPDATE refreshes descriptions and   ║
-- ║  keywords in place, so re-applying never orphans an invoice_costs row. ║
-- ║                                                                        ║
-- ║  `active = FALSE` marks codes that exist in BuilderTrend but must      ║
-- ║  never receive a vendor bill: bid categories and the retention ledger  ║
-- ║  accounts. They are seeded for completeness and hidden from pickers.   ║
-- ╚═══════════════════════════════════════════════════════════════════════╝

INSERT INTO cost_codes (code, base_code, category, description, element_keywords, active)
VALUES
    ('3002 - Concrete Columns', '3002', '3002 - Concrete Ready Mix', 'Concrete Columns', ARRAY['column', 'columns', 'col']::TEXT[], TRUE),
    ('3002 - Concrete Decks', '3002', '3002 - Concrete Ready Mix', 'Concrete Decks', ARRAY['deck', 'decks', 'elevated deck', 'elevated slab', 'podium deck', 'podium slab', 'topping slab', 'suspended slab']::TEXT[], TRUE),
    ('3002 - Concrete Footings', '3002', '3002 - Concrete Ready Mix', 'Concrete Footings', ARRAY['footing', 'footings', 'ftg', 'grade beam', 'grade beams', 'pier', 'piers', 'pile cap', 'pile caps', 'cap', 'caps', 'spread footing', 'continuous footing', 'pile', 'piles']::TEXT[], TRUE),
    ('3002 - Concrete Mat Slab', '3002', '3002 - Concrete Ready Mix', 'Concrete Mat Slab', ARRAY['mat slab', 'mat foundation', 'mat pour', 'mat']::TEXT[], TRUE),
    ('3002 - Concrete Misc', '3002', '3002 - Concrete Ready Mix', 'Concrete Misc', ARRAY['misc', 'miscellaneous', 'pit', 'pits', 'elevator pit', 'sump', 'site concrete', 'equipment pad', 'thrust block']::TEXT[], TRUE),
    ('3002 - Concrete Rat Slab', '3002', '3002 - Concrete Ready Mix', 'Concrete Rat Slab', ARRAY['rat slab', 'mud slab', 'seal slab', 'mudmat']::TEXT[], TRUE),
    ('3002 - Concrete Ready Mix', '3002', '3002 - Concrete Ready Mix', 'Concrete Ready Mix', ARRAY[]::TEXT[], TRUE),
    ('3002 - Concrete Shotcrete', '3002', '3002 - Concrete Ready Mix', 'Concrete Shotcrete', ARRAY['shotcrete', 'gunite', 'shot crete']::TEXT[], TRUE),
    ('3002 - Concrete SOG', '3002', '3002 - Concrete Ready Mix', 'Concrete SOG', ARRAY['sog', 'slab on grade', 'slab-on-grade', 'slab on ground', 'curb', 'curbs', 'pad', 'pads', 'sidewalk', 'flatwork']::TEXT[], TRUE),
    ('3002 - Concrete Walls', '3002', '3002 - Concrete Ready Mix', 'Concrete Walls', ARRAY['wall', 'walls', 'shear wall', 'shear walls', 'basement wall', 'basement walls', 'retaining wall', 'retaining walls', 'misc wall', 'misc walls', 'stem wall', 'core wall', 'tilt wall']::TEXT[], TRUE),
    ('3000 - Concrete', '3000', '3003 - Concrete', 'Concrete', ARRAY[]::TEXT[], TRUE),
    ('3001 - Concrete Consultants & Engineering', '3001', '3003 - Concrete', 'Concrete Consultants & Engineering', ARRAY['testing', 'inspection', 'special inspection', 'consultant', 'engineering', 'lab', 'cylinder', 'break test', 'cefali']::TEXT[], TRUE),
    ('3003 - Concrete Labor', '3003', '3003 - Concrete', 'Concrete Labor', ARRAY['labor', 'placement labor', 'crew']::TEXT[], TRUE),
    ('3004 - Column Rental', '3004', '3003 - Concrete', 'Column Rental', ARRAY['column form', 'sonotube', 'sono tube', 'column rental']::TEXT[], TRUE),
    ('3005 - Reinforcing Steel', '3005', '3003 - Concrete', 'Reinforcing Steel', ARRAY['rebar', 'reinforcing steel', 'reinforcement', 'dowel', 'dowels', 'wwf', 'welded wire', 'mesh', 'epoxy rebar']::TEXT[], TRUE),
    ('3006 - Concrete Finishing', '3006', '3003 - Concrete', 'Concrete Finishing', ARRAY['finishing', 'finish', 'trowel', 'broom finish', 'hard trowel', 'sack', 'rub', 'grind']::TEXT[], TRUE),
    ('3007 - Shotcrete Placement', '3007', '3003 - Concrete', 'Shotcrete Placement', ARRAY['shotcrete placement', 'nozzle', 'nozzleman']::TEXT[], TRUE),
    ('3010 - Equipment Rental & Crane', '3010', '3003 - Concrete', 'Equipment Rental & Crane', ARRAY['crane', 'equipment rental', 'forklift', 'telehandler', 'boom lift', 'skid steer', 'generator']::TEXT[], TRUE),
    ('3011 - Studrails', '3011', '3003 - Concrete', 'Studrails', ARRAY['studrail', 'stud rail', 'shear stud', 'decon']::TEXT[], TRUE),
    ('3012 - Lumber (Purchased)', '3012', '3003 - Concrete', 'Lumber (Purchased)', ARRAY['lumber', 'plywood', 'form lumber', 'dimensional lumber', '2x4', 'plyform', 'shoring lumber', 'form ply']::TEXT[], TRUE),
    ('3013 - Wall Form Rental', '3013', '3003 - Concrete', 'Wall Form Rental', ARRAY['wall form', 'form rental', 'formwork', 'gang form', 'panel form', 'efco', 'symons', 'doka', 'peri']::TEXT[], TRUE),
    ('3014 - Sand & Gravel on SOG', '3014', '3003 - Concrete', 'Sand & Gravel on SOG', ARRAY['sand', 'gravel', 'base rock', 'aggregate base', 'class 2 base', 'crushed rock', '3/4 rock']::TEXT[], TRUE),
    ('3015 - Hardware & Misc', '3015', '3003 - Concrete', 'Hardware & Misc', ARRAY['hardware', 'misc', 'fasteners', 'supplies', 'tie wire', 'chair', 'chairs', 'anchor', 'anchors', 'form oil', 'nails', 'screws', 'blade', 'tool', 'white cap', 'consumables', 'safety']::TEXT[], TRUE),
    ('3016 - Shoring & Falsework', '3016', '3003 - Concrete', 'Shoring & Falsework', ARRAY['shoring', 'falsework', 'shore', 'shores', 'post shore', 'reshore', 'scaffold frame']::TEXT[], TRUE),
    ('3017 - Caissons', '3017', '3003 - Concrete', 'Caissons', ARRAY['caisson', 'caissons', 'drilled pier', 'drilled shaft']::TEXT[], TRUE),
    ('3018 - Construction Waste & Debris', '3018', '3003 - Concrete', 'Construction Waste & Debris', ARRAY['dumpster', 'debris', 'waste', 'disposal', 'haul off', 'bin']::TEXT[], TRUE),
    ('3019 - Concrete General Conditions', '3019', '3003 - Concrete', 'Concrete General Conditions', ARRAY['general conditions', 'temp power', 'temp fence', 'supervision']::TEXT[], TRUE),
    ('3008 - Pumping', '3008', '3008 - Pumping', 'Pumping', ARRAY['pump', 'pumping', 'concrete pump']::TEXT[], TRUE),
    ('3008 - Column Pump', '3008', '3008 - Pumping', 'Column Pump', ARRAY['column pump', 'pump column']::TEXT[], TRUE),
    ('3008 - Deck Pump', '3008', '3008 - Pumping', 'Deck Pump', ARRAY['deck pump', 'pump deck', 'boom pump deck']::TEXT[], TRUE),
    ('3008 - Footing Pump', '3008', '3008 - Pumping', 'Footing Pump', ARRAY['footing pump', 'pump footing']::TEXT[], TRUE),
    ('3008 - Mat Slab Pump', '3008', '3008 - Pumping', 'Mat Slab Pump', ARRAY['mat slab pump', 'pump mat slab']::TEXT[], TRUE),
    ('3008 - Misc/Pits Pump', '3008', '3008 - Pumping', 'Misc/Pits Pump', ARRAY['misc pump', 'pit pump', 'pump misc']::TEXT[], TRUE),
    ('3008 - Placing Boom Rental', '3008', '3008 - Pumping', 'Placing Boom Rental', ARRAY['placing boom', 'boom rental', 'placer']::TEXT[], TRUE),
    ('3008 - Rat Slab Pump', '3008', '3008 - Pumping', 'Rat Slab Pump', ARRAY['rat slab pump', 'pump rat slab']::TEXT[], TRUE),
    ('3008 - SOG Pump', '3008', '3008 - Pumping', 'SOG Pump', ARRAY['sog pump', 'pump sog', 'slab pump']::TEXT[], TRUE),
    ('3008 - Wall Pump', '3008', '3008 - Pumping', 'Wall Pump', ARRAY['wall pump', 'pump wall']::TEXT[], TRUE),
    ('3009 - Trailer Pumping', '3009', '3009 - Trailer Pumping', 'Trailer Pumping', ARRAY['trailer pump', 'line pump', 'trailer pumping']::TEXT[], TRUE),
    ('3009 - Trailer Columns', '3009', '3009 - Trailer Pumping', 'Trailer Columns', ARRAY['trailer pump column', 'line pump column']::TEXT[], TRUE),
    ('3009 - Trailer Decks', '3009', '3009 - Trailer Pumping', 'Trailer Decks', ARRAY['trailer pump deck', 'line pump deck']::TEXT[], TRUE),
    ('3009 - Trailer Footings', '3009', '3009 - Trailer Pumping', 'Trailer Footings', ARRAY['trailer pump footing', 'line pump footing']::TEXT[], TRUE),
    ('3009 - Trailer Mat Slab', '3009', '3009 - Trailer Pumping', 'Trailer Mat Slab', ARRAY['trailer pump mat slab']::TEXT[], TRUE),
    ('3009 - Trailer Misc', '3009', '3009 - Trailer Pumping', 'Trailer Misc', ARRAY['trailer pump misc']::TEXT[], TRUE),
    ('3009 - Trailer Rat Slab', '3009', '3009 - Trailer Pumping', 'Trailer Rat Slab', ARRAY['trailer pump rat slab']::TEXT[], TRUE),
    ('3009 - Trailer SOG', '3009', '3009 - Trailer Pumping', 'Trailer SOG', ARRAY['trailer pump sog', 'line pump sog']::TEXT[], TRUE),
    ('3009 - Trailer Walls', '3009', '3009 - Trailer Pumping', 'Trailer Walls', ARRAY['trailer pump wall', 'line pump wall']::TEXT[], TRUE),
    ('4000 - Masonry', '4000', '4000 - Masonry', 'Masonry', ARRAY['masonry']::TEXT[], TRUE),
    ('4001 - CMU', '4001', '4000 - Masonry', 'CMU', ARRAY['cmu', 'block', 'masonry block', 'concrete block', 'grout']::TEXT[], TRUE),
    ('4002 - Brick & Vaneer', '4002', '4000 - Masonry', 'Brick & Vaneer', ARRAY['brick', 'veneer', 'vaneer', 'stone veneer']::TEXT[], TRUE),
    ('Site CMU', NULL, 'Bids', 'Site CMU', ARRAY[]::TEXT[], FALSE),
    ('Site Concrete', NULL, 'Bids', 'Site Concrete', ARRAY[]::TEXT[], FALSE),
    ('Structural CMU', NULL, 'Bids', 'Structural CMU', ARRAY[]::TEXT[], FALSE),
    ('Structural Concrete', NULL, 'Bids', 'Structural Concrete', ARRAY[]::TEXT[], FALSE),
    ('Buildertrend Flat Rate', NULL, 'Buildertrend Default', 'Buildertrend Flat Rate', ARRAY[]::TEXT[], FALSE),
    ('Retention', NULL, 'General', 'Retention', ARRAY[]::TEXT[], FALSE),
    ('Retention Payable', NULL, 'General', 'Retention Payable', ARRAY[]::TEXT[], FALSE),
    ('1000 - General Requirements', '1000', 'QuickBooks Import', 'General Requirements', ARRAY[]::TEXT[], TRUE),
    ('1001 - Surveying', '1001', 'QuickBooks Import', 'Surveying', ARRAY['survey', 'surveying', 'layout', 'staking']::TEXT[], TRUE),
    ('1002 - Construction Management Services', '1002', 'QuickBooks Import', 'Construction Management Services', ARRAY[]::TEXT[], TRUE),
    ('1003 - Temporary Facilities', '1003', 'QuickBooks Import', 'Temporary Facilities', ARRAY[]::TEXT[], TRUE),
    ('1004 - Portable Toilets', '1004', 'QuickBooks Import', 'Portable Toilets', ARRAY['portable toilet', 'porta potty', 'restroom rental']::TEXT[], TRUE),
    ('1005 - Security Services', '1005', 'QuickBooks Import', 'Security Services', ARRAY[]::TEXT[], TRUE),
    ('1006 - Construction Aids', '1006', 'QuickBooks Import', 'Construction Aids', ARRAY[]::TEXT[], TRUE),
    ('1007 - Quality Control Services', '1007', 'QuickBooks Import', 'Quality Control Services', ARRAY['quality control', 'qc', 'testing agency']::TEXT[], TRUE),
    ('1008 - Construction Equipment', '1008', 'QuickBooks Import', 'Construction Equipment', ARRAY['equipment', 'machine rental']::TEXT[], TRUE),
    ('1009 - Construction Cleaning Services', '1009', 'QuickBooks Import', 'Construction Cleaning Services', ARRAY[]::TEXT[], TRUE),
    ('1010 - Traffic Control Rental', '1010', 'QuickBooks Import', 'Traffic Control Rental', ARRAY['traffic control', 'k-rail', 'cones', 'flagging']::TEXT[], TRUE),
    ('1011 - Temporary Utilities', '1011', 'QuickBooks Import', 'Temporary Utilities', ARRAY[]::TEXT[], TRUE),
    ('10000 - Specialties', '10000', 'QuickBooks Import', 'Specialties', ARRAY[]::TEXT[], TRUE),
    ('10001 - Postal Specialties', '10001', 'QuickBooks Import', 'Postal Specialties', ARRAY[]::TEXT[], TRUE),
    ('10002 - Partitions', '10002', 'QuickBooks Import', 'Partitions', ARRAY[]::TEXT[], TRUE),
    ('10003 - Storage/Closet Shelving''s', '10003', 'QuickBooks Import', 'Storage/Closet Shelving''s', ARRAY[]::TEXT[], TRUE),
    ('10004 - Lockers', '10004', 'QuickBooks Import', 'Lockers', ARRAY[]::TEXT[], TRUE),
    ('10005 - Shade', '10005', 'QuickBooks Import', 'Shade', ARRAY[]::TEXT[], TRUE),
    ('10006 - Fire place & Stoves', '10006', 'QuickBooks Import', 'Fire place & Stoves', ARRAY[]::TEXT[], TRUE),
    ('10007 - Flagpoles', '10007', 'QuickBooks Import', 'Flagpoles', ARRAY[]::TEXT[], TRUE),
    ('10008 - Louvers, Vents & Screens', '10008', 'QuickBooks Import', 'Louvers, Vents & Screens', ARRAY[]::TEXT[], TRUE),
    ('10009 - Cubicles', '10009', 'QuickBooks Import', 'Cubicles', ARRAY[]::TEXT[], TRUE),
    ('10010 - Fire Extinguisher', '10010', 'QuickBooks Import', 'Fire Extinguisher', ARRAY[]::TEXT[], TRUE),
    ('10011 - Interior & Exterior Signs', '10011', 'QuickBooks Import', 'Interior & Exterior Signs', ARRAY[]::TEXT[], TRUE),
    ('11000 - Equipment', '11000', 'QuickBooks Import', 'Equipment', ARRAY[]::TEXT[], TRUE),
    ('11001 - Maintenance Equipment', '11001', 'QuickBooks Import', 'Maintenance Equipment', ARRAY[]::TEXT[], TRUE),
    ('11002 - Comm. Laundry & Dry Clean', '11002', 'QuickBooks Import', 'Comm. Laundry & Dry Clean', ARRAY[]::TEXT[], TRUE),
    ('11003 - Vending Equipment', '11003', 'QuickBooks Import', 'Vending Equipment', ARRAY[]::TEXT[], TRUE),
    ('11004 - Parking Control Equipment', '11004', 'QuickBooks Import', 'Parking Control Equipment', ARRAY[]::TEXT[], TRUE),
    ('11005 - Kitchen Equipment', '11005', 'QuickBooks Import', 'Kitchen Equipment', ARRAY[]::TEXT[], TRUE),
    ('11006 - Athletics Equipment', '11006', 'QuickBooks Import', 'Athletics Equipment', ARRAY[]::TEXT[], TRUE),
    ('11007 - Medical Equipment', '11007', 'QuickBooks Import', 'Medical Equipment', ARRAY[]::TEXT[], TRUE),
    ('11008 - Bike Rack', '11008', 'QuickBooks Import', 'Bike Rack', ARRAY[]::TEXT[], TRUE),
    ('11009 - Amenities Equopments', '11009', 'QuickBooks Import', 'Amenities Equopments', ARRAY[]::TEXT[], TRUE),
    ('11010 - EV Car Equipment', '11010', 'QuickBooks Import', 'EV Car Equipment', ARRAY[]::TEXT[], TRUE),
    ('12000 - Furnishing', '12000', 'QuickBooks Import', 'Furnishing', ARRAY[]::TEXT[], TRUE),
    ('13000 - Special Construction', '13000', 'QuickBooks Import', 'Special Construction', ARRAY[]::TEXT[], TRUE),
    ('13001 - Pools', '13001', 'QuickBooks Import', 'Pools', ARRAY[]::TEXT[], TRUE),
    ('13002 - Solar Energy Systems', '13002', 'QuickBooks Import', 'Solar Energy Systems', ARRAY[]::TEXT[], TRUE),
    ('13003 - Building Automation System', '13003', 'QuickBooks Import', 'Building Automation System', ARRAY[]::TEXT[], TRUE),
    ('14000 - Conveying System', '14000', 'QuickBooks Import', 'Conveying System', ARRAY[]::TEXT[], TRUE),
    ('14001 - Elevators', '14001', 'QuickBooks Import', 'Elevators', ARRAY[]::TEXT[], TRUE),
    ('14002 - Chutes', '14002', 'QuickBooks Import', 'Chutes', ARRAY[]::TEXT[], TRUE),
    ('14003 - Scaffolding', '14003', 'QuickBooks Import', 'Scaffolding', ARRAY[]::TEXT[], TRUE),
    ('14004 - Moving Stairs & Walks', '14004', 'QuickBooks Import', 'Moving Stairs & Walks', ARRAY[]::TEXT[], TRUE),
    ('14005 - Vehicle Lifts', '14005', 'QuickBooks Import', 'Vehicle Lifts', ARRAY[]::TEXT[], TRUE),
    ('15000 - HVAC', '15000', 'QuickBooks Import', 'HVAC', ARRAY[]::TEXT[], TRUE),
    ('15001 - HVAC System', '15001', 'QuickBooks Import', 'HVAC System', ARRAY[]::TEXT[], TRUE),
    ('16000 - Electrical & Lighting', '16000', 'QuickBooks Import', 'Electrical & Lighting', ARRAY[]::TEXT[], TRUE),
    ('16001 - Electrical System', '16001', 'QuickBooks Import', 'Electrical System', ARRAY[]::TEXT[], TRUE),
    ('16002 - A/V Systems (Security)', '16002', 'QuickBooks Import', 'A/V Systems (Security)', ARRAY[]::TEXT[], TRUE),
    ('16003 - D/V Systems (Low Voltage)', '16003', 'QuickBooks Import', 'D/V Systems (Low Voltage)', ARRAY[]::TEXT[], TRUE),
    ('16004 - Das System', '16004', 'QuickBooks Import', 'Das System', ARRAY[]::TEXT[], TRUE),
    ('16005 - EV Charging Station Conduit/Wire', '16005', 'QuickBooks Import', 'EV Charging Station Conduit/Wire', ARRAY[]::TEXT[], TRUE),
    ('16006 - Vault room (New)', '16006', 'QuickBooks Import', 'Vault room (New)', ARRAY[]::TEXT[], TRUE),
    ('16007 - CCTV Camera', '16007', 'QuickBooks Import', 'CCTV Camera', ARRAY[]::TEXT[], TRUE),
    ('17000 - Plumbing', '17000', 'QuickBooks Import', 'Plumbing', ARRAY[]::TEXT[], TRUE),
    ('17001 - Plumbing System', '17001', 'QuickBooks Import', 'Plumbing System', ARRAY[]::TEXT[], TRUE),
    ('17002 - Drywell System', '17002', 'QuickBooks Import', 'Drywell System', ARRAY[]::TEXT[], TRUE),
    ('18000 - Fire Sprinkler & Fire Ala', '18000', 'QuickBooks Import', 'Fire Sprinkler & Fire Ala', ARRAY[]::TEXT[], TRUE),
    ('18001 - Fire Sprinkler', '18001', 'QuickBooks Import', 'Fire Sprinkler', ARRAY[]::TEXT[], TRUE),
    ('18002 - Fire Alarm', '18002', 'QuickBooks Import', 'Fire Alarm', ARRAY[]::TEXT[], TRUE),
    ('19000 - Hoist System', '19000', 'QuickBooks Import', 'Hoist System', ARRAY[]::TEXT[], TRUE),
    ('19001 - Manlift', '19001', 'QuickBooks Import', 'Manlift', ARRAY[]::TEXT[], TRUE),
    ('19002 - Tower Crane', '19002', 'QuickBooks Import', 'Tower Crane', ARRAY[]::TEXT[], TRUE),
    ('19003 - Hoist & Crane', '19003', 'QuickBooks Import', 'Hoist & Crane', ARRAY[]::TEXT[], TRUE),
    ('2000 - Site Construction', '2000', 'QuickBooks Import', 'Site Construction', ARRAY[]::TEXT[], TRUE),
    ('2001 - Demolition', '2001', 'QuickBooks Import', 'Demolition', ARRAY[]::TEXT[], TRUE),
    ('2002 - Hazardous Material Removal', '2002', 'QuickBooks Import', 'Hazardous Material Removal', ARRAY[]::TEXT[], TRUE),
    ('2003 - Site Preparation', '2003', 'QuickBooks Import', 'Site Preparation', ARRAY['site prep', 'clear and grub', 'demo prep']::TEXT[], TRUE),
    ('2004 - Earth Shoring', '2004', 'QuickBooks Import', 'Earth Shoring', ARRAY['soldier pile', 'tieback', 'lagging', 'earth shoring']::TEXT[], TRUE),
    ('2005 - Earthwork', '2005', 'QuickBooks Import', 'Earthwork', ARRAY['earthwork', 'grading', 'excavation', 'backfill', 'import soil']::TEXT[], TRUE),
    ('2006 - Dewatering', '2006', 'QuickBooks Import', 'Dewatering', ARRAY['dewatering', 'well point', 'sump pump rental']::TEXT[], TRUE),
    ('2007 - Site Utilities', '2007', 'QuickBooks Import', 'Site Utilities', ARRAY[]::TEXT[], TRUE),
    ('2008 - Site Improvement', '2008', 'QuickBooks Import', 'Site Improvement', ARRAY[]::TEXT[], TRUE),
    ('2009 - Off-site Improvement', '2009', 'QuickBooks Import', 'Off-site Improvement', ARRAY[]::TEXT[], TRUE),
    ('2010 - Fencens & Gates', '2010', 'QuickBooks Import', 'Fencens & Gates', ARRAY[]::TEXT[], TRUE),
    ('2011 - Landscape & Irrigation', '2011', 'QuickBooks Import', 'Landscape & Irrigation', ARRAY[]::TEXT[], TRUE),
    ('20000 - Soft Cost', '20000', 'QuickBooks Import', 'Soft Cost', ARRAY[]::TEXT[], TRUE),
    ('20001 - Consultants (Arch, Eng.)', '20001', 'QuickBooks Import', 'Consultants (Arch, Eng.)', ARRAY[]::TEXT[], TRUE),
    ('20002 - Plan Check', '20002', 'QuickBooks Import', 'Plan Check', ARRAY[]::TEXT[], TRUE),
    ('20003 - Project Permits', '20003', 'QuickBooks Import', 'Project Permits', ARRAY[]::TEXT[], TRUE),
    ('20004 - Accounting', '20004', 'QuickBooks Import', 'Accounting', ARRAY[]::TEXT[], TRUE),
    ('20005 - Insurance & Bonding', '20005', 'QuickBooks Import', 'Insurance & Bonding', ARRAY[]::TEXT[], TRUE),
    ('20005.1 - General Liability Insur', '20005.1', 'QuickBooks Import', 'General Liability Insur', ARRAY[]::TEXT[], TRUE),
    ('20005.2 - Health Insurance', '20005.2', 'QuickBooks Import', 'Health Insurance', ARRAY[]::TEXT[], TRUE),
    ('20005.3 - Auto Insurance', '20005.3', 'QuickBooks Import', 'Auto Insurance', ARRAY[]::TEXT[], TRUE),
    ('20005.4 - EPLI Fee', '20005.4', 'QuickBooks Import', 'EPLI Fee', ARRAY[]::TEXT[], TRUE),
    ('20005.5 - Workers Comp Insurance', '20005.5', 'QuickBooks Import', 'Workers Comp Insurance', ARRAY[]::TEXT[], TRUE),
    ('20005.6 - OCIP insurance', '20005.6', 'QuickBooks Import', 'OCIP insurance', ARRAY[]::TEXT[], TRUE),
    ('20005.7 - Bonding', '20005.7', 'QuickBooks Import', 'Bonding', ARRAY[]::TEXT[], TRUE),
    ('20006 - Auto and Truck Expenses', '20006', 'QuickBooks Import', 'Auto and Truck Expenses', ARRAY[]::TEXT[], TRUE),
    ('20006.1 - Auto Lease', '20006.1', 'QuickBooks Import', 'Auto Lease', ARRAY[]::TEXT[], TRUE),
    ('20006.2 - Auto Rentals', '20006.2', 'QuickBooks Import', 'Auto Rentals', ARRAY[]::TEXT[], TRUE),
    ('20006.3 - Auto Fuel', '20006.3', 'QuickBooks Import', 'Auto Fuel', ARRAY[]::TEXT[], TRUE),
    ('20006.4 - Maintenance & Repairs', '20006.4', 'QuickBooks Import', 'Maintenance & Repairs', ARRAY[]::TEXT[], TRUE),
    ('20006.5 - Mileage Reimbursement', '20006.5', 'QuickBooks Import', 'Mileage Reimbursement', ARRAY[]::TEXT[], TRUE),
    ('20006.6 - Registration', '20006.6', 'QuickBooks Import', 'Registration', ARRAY[]::TEXT[], TRUE),
    ('20006.7 - Transportation', '20006.7', 'QuickBooks Import', 'Transportation', ARRAY[]::TEXT[], TRUE),
    ('20007 - Design Supervision', '20007', 'QuickBooks Import', 'Design Supervision', ARRAY[]::TEXT[], TRUE),
    ('20008 - Finance', '20008', 'QuickBooks Import', 'Finance', ARRAY[]::TEXT[], TRUE),
    ('20009 - Safety Services', '20009', 'QuickBooks Import', 'Safety Services', ARRAY[]::TEXT[], TRUE),
    ('20010 - Contingency', '20010', 'QuickBooks Import', 'Contingency', ARRAY[]::TEXT[], TRUE),
    ('20011 - Commissions', '20011', 'QuickBooks Import', 'Commissions', ARRAY[]::TEXT[], TRUE),
    ('20012- Office Supplies', '20012', 'QuickBooks Import', 'Office Supplies', ARRAY[]::TEXT[], TRUE),
    ('20013 - Postage and Delivery', '20013', 'QuickBooks Import', 'Postage and Delivery', ARRAY[]::TEXT[], TRUE),
    ('20014 - Meals and Entertainment', '20014', 'QuickBooks Import', 'Meals and Entertainment', ARRAY[]::TEXT[], TRUE),
    ('20015 - Pre-Construction', '20015', 'QuickBooks Import', 'Pre-Construction', ARRAY[]::TEXT[], TRUE),
    ('20016 - Freight', '20016', 'QuickBooks Import', 'Freight', ARRAY[]::TEXT[], TRUE),
    ('20017 - Travel & Lodge', '20017', 'QuickBooks Import', 'Travel & Lodge', ARRAY[]::TEXT[], TRUE),
    ('20018 - Donations', '20018', 'QuickBooks Import', 'Donations', ARRAY[]::TEXT[], TRUE),
    ('20019 - Business Licenses & Permit', '20019', 'QuickBooks Import', 'Business Licenses & Permit', ARRAY[]::TEXT[], TRUE),
    ('20020 - Office Expense', '20020', 'QuickBooks Import', 'Office Expense', ARRAY[]::TEXT[], TRUE),
    ('20021- Medical Expenses', '20021', 'QuickBooks Import', 'Medical Expenses', ARRAY[]::TEXT[], TRUE),
    ('20022 - Utilities', '20022', 'QuickBooks Import', 'Utilities', ARRAY[]::TEXT[], TRUE),
    ('20023- Telephone Expense', '20023', 'QuickBooks Import', 'Telephone Expense', ARRAY[]::TEXT[], TRUE),
    ('20024 - Rent Expense', '20024', 'QuickBooks Import', 'Rent Expense', ARRAY[]::TEXT[], TRUE),
    ('20025 - Waste Services', '20025', 'QuickBooks Import', 'Waste Services', ARRAY[]::TEXT[], TRUE),
    ('20026 - Educational Services', '20026', 'QuickBooks Import', 'Educational Services', ARRAY[]::TEXT[], TRUE),
    ('20027 - Dues and Subscriptions', '20027', 'QuickBooks Import', 'Dues and Subscriptions', ARRAY[]::TEXT[], TRUE),
    ('20028 - Computer & Internet Ex', '20028', 'QuickBooks Import', 'Computer & Internet Ex', ARRAY[]::TEXT[], TRUE),
    ('20029- Payroll Expenses', '20029', 'QuickBooks Import', 'Payroll Expenses', ARRAY[]::TEXT[], TRUE),
    ('20030 - Payroll Processing Fees', '20030', 'QuickBooks Import', 'Payroll Processing Fees', ARRAY[]::TEXT[], TRUE),
    ('20031 - Payroll Delivery charge', '20031', 'QuickBooks Import', 'Payroll Delivery charge', ARRAY[]::TEXT[], TRUE),
    ('20032 - Payroll Expense', '20032', 'QuickBooks Import', 'Payroll Expense', ARRAY[]::TEXT[], TRUE),
    ('20033 - Equipment Lease', '20033', 'QuickBooks Import', 'Equipment Lease', ARRAY[]::TEXT[], TRUE),
    ('20034 - Equipment Maintenance & Repair', '20034', 'QuickBooks Import', 'Equipment Maintenance & Repair', ARRAY[]::TEXT[], TRUE),
    ('20035 - Equipment Maintenance &', '20035', 'QuickBooks Import', 'Equipment Maintenance &', ARRAY[]::TEXT[], TRUE),
    ('20036 - Advertising, Promotion', '20036', 'QuickBooks Import', 'Advertising, Promotion', ARRAY[]::TEXT[], TRUE),
    ('20037 - Sales & Marketing', '20037', 'QuickBooks Import', 'Sales & Marketing', ARRAY[]::TEXT[], TRUE),
    ('20038 - Blueprints & Reproduct', '20038', 'QuickBooks Import', 'Blueprints & Reproduct', ARRAY[]::TEXT[], TRUE),
    ('20039 - Bank Service Charges', '20039', 'QuickBooks Import', 'Bank Service Charges', ARRAY[]::TEXT[], TRUE),
    ('20040 - Late Fees/Penalties', '20040', 'QuickBooks Import', 'Late Fees/Penalties', ARRAY[]::TEXT[], TRUE),
    ('20041 - Citations', '20041', 'QuickBooks Import', 'Citations', ARRAY[]::TEXT[], TRUE),
    ('20042 - Professional Fees', '20042', 'QuickBooks Import', 'Professional Fees', ARRAY[]::TEXT[], TRUE),
    ('20043 - Credit Card Fee', '20043', 'QuickBooks Import', 'Credit Card Fee', ARRAY[]::TEXT[], TRUE),
    ('20044 - Taxes', '20044', 'QuickBooks Import', 'Taxes', ARRAY[]::TEXT[], TRUE),
    ('20045 - GC Fee', '20045', 'QuickBooks Import', 'GC Fee', ARRAY[]::TEXT[], TRUE),
    ('20046 - Damages', '20046', 'QuickBooks Import', 'Damages', ARRAY[]::TEXT[], TRUE),
    ('5000 - Metals', '5000', 'QuickBooks Import', 'Metals', ARRAY[]::TEXT[], TRUE),
    ('5001 - Structural Steel Framing', '5001', 'QuickBooks Import', 'Structural Steel Framing', ARRAY['structural steel', 'embeds', 'embed plate', 'steel beam']::TEXT[], TRUE),
    ('5002 - Expansion Control', '5002', 'QuickBooks Import', 'Expansion Control', ARRAY['expansion joint', 'control joint', 'joint filler']::TEXT[], TRUE),
    ('5003 - Metal Handrails & Railings', '5003', 'QuickBooks Import', 'Metal Handrails & Railings', ARRAY[]::TEXT[], TRUE),
    ('5004 - Sheet Metal', '5004', 'QuickBooks Import', 'Sheet Metal', ARRAY[]::TEXT[], TRUE),
    ('5005 - Cable Railing', '5005', 'QuickBooks Import', 'Cable Railing', ARRAY[]::TEXT[], TRUE),
    ('5006 - Metal Bollard', '5006', 'QuickBooks Import', 'Metal Bollard', ARRAY[]::TEXT[], TRUE),
    ('6000 - Millworks & Carpentry', '6000', 'QuickBooks Import', 'Millworks & Carpentry', ARRAY[]::TEXT[], TRUE),
    ('6001 - Rough Carpentry', '6001', 'QuickBooks Import', 'Rough Carpentry', ARRAY['rough carpentry', 'framing lumber', 'blocking']::TEXT[], TRUE),
    ('6002 - Kitchen Cabinets / Counter', '6002', 'QuickBooks Import', 'Kitchen Cabinets / Counter', ARRAY[]::TEXT[], TRUE),
    ('6003 - Vanities', '6003', 'QuickBooks Import', 'Vanities', ARRAY[]::TEXT[], TRUE),
    ('6004 - Finish Carpentry / Arch. W', '6004', 'QuickBooks Import', 'Finish Carpentry / Arch. W', ARRAY[]::TEXT[], TRUE),
    ('6005 - Exterior Trim & Decks', '6005', 'QuickBooks Import', 'Exterior Trim & Decks', ARRAY[]::TEXT[], TRUE),
    ('7000 - Thermal & Moisture Protect', '7000', 'QuickBooks Import', 'Thermal & Moisture Protect', ARRAY[]::TEXT[], TRUE),
    ('7001 - Waterproofing', '7001', 'QuickBooks Import', 'Waterproofing', ARRAY['waterproofing', 'membrane', 'vapor barrier', 'visqueen', 'damp proofing']::TEXT[], TRUE),
    ('7002 - Insulation', '7002', 'QuickBooks Import', 'Insulation', ARRAY[]::TEXT[], TRUE),
    ('7003 - Fireproofing', '7003', 'QuickBooks Import', 'Fireproofing', ARRAY['fireproofing', 'intumescent', 'spray fireproofing']::TEXT[], TRUE),
    ('7004 - Roofing', '7004', 'QuickBooks Import', 'Roofing', ARRAY[]::TEXT[], TRUE),
    ('7005 - Roof Flashing', '7005', 'QuickBooks Import', 'Roof Flashing', ARRAY[]::TEXT[], TRUE),
    ('7006 - Skylights', '7006', 'QuickBooks Import', 'Skylights', ARRAY[]::TEXT[], TRUE),
    ('8000 - Door & Glazing', '8000', 'QuickBooks Import', 'Door & Glazing', ARRAY[]::TEXT[], TRUE),
    ('8001 - Metal Doors & Frames', '8001', 'QuickBooks Import', 'Metal Doors & Frames', ARRAY[]::TEXT[], TRUE),
    ('8002 - Wood & Plastic Doors', '8002', 'QuickBooks Import', 'Wood & Plastic Doors', ARRAY[]::TEXT[], TRUE),
    ('8003 - Metal Windows & Frames', '8003', 'QuickBooks Import', 'Metal Windows & Frames', ARRAY[]::TEXT[], TRUE),
    ('8004 - Wood & Plastic Windows', '8004', 'QuickBooks Import', 'Wood & Plastic Windows', ARRAY[]::TEXT[], TRUE),
    ('8005 - Storefront, Glazing & Curt', '8005', 'QuickBooks Import', 'Storefront, Glazing & Curt', ARRAY[]::TEXT[], TRUE),
    ('8006 - Shower Doors', '8006', 'QuickBooks Import', 'Shower Doors', ARRAY[]::TEXT[], TRUE),
    ('8007 - Glass Guardrails', '8007', 'QuickBooks Import', 'Glass Guardrails', ARRAY[]::TEXT[], TRUE),
    ('8008 - Overhead Doors (Rollup Doors, Gates,…)', '8008', 'QuickBooks Import', 'Overhead Doors (Rollup Doors, Gates,…)', ARRAY[]::TEXT[], TRUE),
    ('9000 - Finishes', '9000', 'QuickBooks Import', 'Finishes', ARRAY[]::TEXT[], TRUE),
    ('9001 - Metal Stud', '9001', 'QuickBooks Import', 'Metal Stud', ARRAY[]::TEXT[], TRUE),
    ('9002 - Drywall & Insulation', '9002', 'QuickBooks Import', 'Drywall & Insulation', ARRAY[]::TEXT[], TRUE),
    ('9003 - Tile & Stone', '9003', 'QuickBooks Import', 'Tile & Stone', ARRAY[]::TEXT[], TRUE),
    ('9004 - Wood Flooring', '9004', 'QuickBooks Import', 'Wood Flooring', ARRAY[]::TEXT[], TRUE),
    ('9005 - Carpet Flooring', '9005', 'QuickBooks Import', 'Carpet Flooring', ARRAY[]::TEXT[], TRUE),
    ('9006 - Special Wall Covering', '9006', 'QuickBooks Import', 'Special Wall Covering', ARRAY[]::TEXT[], TRUE),
    ('9007 - Special Floor Covering', '9007', 'QuickBooks Import', 'Special Floor Covering', ARRAY[]::TEXT[], TRUE),
    ('9008 - Painting', '9008', 'QuickBooks Import', 'Painting', ARRAY[]::TEXT[], TRUE),
    ('9009 - Lath & Plaster', '9009', 'QuickBooks Import', 'Lath & Plaster', ARRAY[]::TEXT[], TRUE),
    ('9010 - Acoustical Ceiling', '9010', 'QuickBooks Import', 'Acoustical Ceiling', ARRAY[]::TEXT[], TRUE),
    ('9011 - Parking Stripping', '9011', 'QuickBooks Import', 'Parking Stripping', ARRAY['striping', 'stripping', 'parking stripe']::TEXT[], TRUE)
ON CONFLICT (code) DO UPDATE SET
    base_code        = EXCLUDED.base_code,
    category         = EXCLUDED.category,
    description      = EXCLUDED.description,
    element_keywords = EXCLUDED.element_keywords,
    active           = EXCLUDED.active,
    updated_at       = NOW();
